<?php
/**
 * Core Presets Manager.
 * Single source of truth for all presets (Wizard & Admin).
 *
 * @package LoginDesignerWP
 */

if (!defined('ABSPATH')) {
    exit;
}

class Login_Designer_WP_Presets_Core
{

    /**
     * Get all available presets.
     *
     * @return array
     */
    public static function get_presets()
    {
        return array(
            // ============================================
            // MODERN
            // ============================================
            'modern_light' => array(
                'name' => __('Modern Light', 'logindesignerwp'),
                'category' => 'modern',
                'is_pro' => false,
                'preview' => array(
                    'bg' => '#f8fafc',
                    'form_bg' => '#fff',
                    'form_border' => '1px solid #e2e8f0',
                    'input_bg' => '#f1f5f9',
                    'button_bg' => '#3b82f6',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#f8fafc',
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 12,
                    'form_border_color' => '#e2e8f0',
                    'label_text_color' => '#334155',
                    'input_bg_color' => '#ffffff',
                    'input_text_color' => '#1e293b',
                    'input_border_color' => '#cbd5e1',
                    'button_bg' => '#3b82f6',
                    'button_bg_hover' => '#2563eb',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 8,
                    'glass_enabled' => 0,
                    'below_form_link_color' => '#64748b',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'modern_dark' => array(
                'name' => __('Modern Dark', 'logindesignerwp'),
                'category' => 'modern',
                'is_pro' => false,
                'preview' => array(
                    'bg' => '#0f172a',
                    'form_bg' => '#1e293b',
                    'form_border' => '1px solid #334155',
                    'input_bg' => '#0f172a',
                    'button_bg' => '#3b82f6',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#0f172a',
                    'form_bg_color' => '#1e293b',
                    'form_border_radius' => 12,
                    'form_border_color' => '#334155',
                    'label_text_color' => '#e2e8f0',
                    'input_bg_color' => '#0f172a',
                    'input_text_color' => '#f1f5f9',
                    'input_border_color' => '#475569',
                    'button_bg' => '#3b82f6',
                    'button_bg_hover' => '#2563eb',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 8,
                    'glass_enabled' => 0,
                    'below_form_link_color' => '#94a3b8',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // MINIMAL
            // ============================================
            'minimal' => array(
                'name' => __('Minimal', 'logindesignerwp'),
                'category' => 'minimal',
                'is_pro' => false,
                'preview' => array(
                    'bg' => '#fff',
                    'form_bg' => '#fff',
                    'form_border' => '1px solid #e5e7eb',
                    'input_bg' => '#f9fafb',
                    'button_bg' => '#111827',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#ffffff',
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 0,
                    'form_border_color' => '#e5e7eb',
                    'label_text_color' => '#111827',
                    'input_bg_color' => '#f9fafb',
                    'input_text_color' => '#111827',
                    'input_border_color' => '#d1d5db',
                    'button_bg' => '#111827',
                    'button_bg_hover' => '#374151',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 4,
                    'glass_enabled' => 0,
                    'below_form_link_color' => '#6b7280',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // PRO: GLASS
            // ============================================
            'glassmorphism' => array(
                'name' => __('Glassmorphism', 'logindesignerwp'),
                'category' => 'glass',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #667eea, #764ba2)',
                    'form_bg' => 'rgba(255,255,255,0.15)',
                    'form_border' => '1px solid rgba(255,255,255,0.3)',
                    'input_bg' => 'rgba(255,255,255,0.2)',
                    'button_bg' => '#ffffff',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#667eea',
                    'background_gradient_2' => '#764ba2',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'gradient_position' => 'center center',
                    'form_bg_color' => 'rgba(255,255,255,0.15)',
                    'form_border_radius' => 20,
                    'form_border_color' => 'rgba(255,255,255,0.3)',
                    'label_text_color' => '#ffffff',
                    'input_bg_color' => 'rgba(255,255,255,0.2)',
                    'input_text_color' => '#ffffff',
                    'input_border_color' => 'rgba(255,255,255,0.3)',
                    'button_bg' => '#ffffff',
                    'button_bg_hover' => '#f0f0f0',
                    'button_text_color' => '#667eea',
                    'button_border_radius' => 999,
                    'glass_enabled' => 1,
                    'glass_blur' => 10,
                    'glass_transparency' => 85,
                    'below_form_link_color' => '#ffffff',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // PRO: NEON
            // ============================================
            'neon_glow' => array(
                'name' => __('Neon Glow', 'logindesignerwp'),
                'category' => 'dark',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#0a0a0a',
                    'form_bg' => '#141414',
                    'form_border' => '1px solid #22d3ee',
                    'input_bg' => '#16213e',
                    'button_bg' => 'linear-gradient(90deg, #00d4ff, #00ff88)',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#0a0a0a',
                    'form_bg_color' => '#141414',
                    'form_border_radius' => 16,
                    'form_border_color' => '#22d3ee',
                    'label_text_color' => '#22d3ee',
                    'input_bg_color' => '#0a0a0a',
                    'input_text_color' => '#f0f0f0',
                    'input_border_color' => '#22d3ee',
                    'button_bg' => '#22d3ee',
                    'button_bg_hover' => '#06b6d4',
                    'button_text_color' => '#0a0a0a',
                    'button_border_radius' => 8,
                    'glass_enabled' => 0,
                    'below_form_link_color' => '#22d3ee',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // BUSINESS / CORPORATE
            // ============================================
            'corporate' => array(
                'name' => __('Corporate', 'logindesignerwp'),
                'category' => 'business',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#1e3a5f',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #d1d5db',
                    'input_bg' => '#f9fafb',
                    'button_bg' => '#1e3a5f',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#1e3a5f',
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 4,
                    'form_border_color' => '#d1d5db',
                    'label_text_color' => '#1f2937',
                    'input_bg_color' => '#f9fafb',
                    'input_text_color' => '#111827',
                    'input_border_color' => '#9ca3af',
                    'button_bg' => '#1e3a5f',
                    'button_bg_hover' => '#0f2744',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 4,
                    'glass_enabled' => 0,
                    'below_form_link_color' => '#cbd5e1',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'startup' => array(
                'name' => __('Startup', 'logindesignerwp'),
                'category' => 'business',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #4f46e5, #ec4899)',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #e0e7ff',
                    'input_bg' => '#fcfcfc',
                    'button_bg' => '#4f46e5',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#4f46e5',
                    'background_gradient_2' => '#ec4899',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 8,
                    'form_border_color' => '#e0e7ff',
                    'label_text_color' => '#3730a3',
                    'input_bg_color' => '#fcfcfc',
                    'input_text_color' => '#1e1b4b',
                    'input_border_color' => '#c7d2fe',
                    'button_bg' => '#4f46e5',
                    'button_bg_hover' => '#4338ca',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 6,
                    'below_form_link_color' => '#e0e7ff',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'finance_gray' => array(
                'name' => __('Finance Gray', 'logindesignerwp'),
                'category' => 'business',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#374151',
                    'form_bg' => '#1f2937',
                    'form_border' => '1px solid #4b5563',
                    'input_bg' => '#111827',
                    'button_bg' => '#10b981',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#374151',
                    'form_bg_color' => '#1f2937',
                    'form_border_radius' => 4,
                    'form_border_color' => '#4b5563',
                    'label_text_color' => '#e5e7eb',
                    'input_bg_color' => '#111827',
                    'input_text_color' => '#f3f4f6',
                    'input_border_color' => '#374151',
                    'button_bg' => '#10b981',
                    'button_bg_hover' => '#059669',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 4,
                    'below_form_link_color' => '#d1d5db',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // NATURE / GRADIENTS
            // ============================================
            'sunset' => array(
                'name' => __('Sunset', 'logindesignerwp'),
                'category' => 'nature',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #ff6b6b, #feca57)',
                    'form_bg' => 'rgba(255,255,255,0.95)',
                    'form_border' => 'none',
                    'input_bg' => '#fff4f4',
                    'button_bg' => 'linear-gradient(90deg, #ff6b6b, #feca57)',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#ff6b6b',
                    'background_gradient_2' => '#feca57',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 12,
                    'form_border_color' => '#fecaca',
                    'label_text_color' => '#1f2937',
                    'input_bg_color' => '#fff4f4',
                    'input_text_color' => '#1f2937',
                    'input_border_color' => '#fed7aa',
                    'button_bg' => '#ea580c',
                    'button_bg_hover' => '#c2410c',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 999,
                    'below_form_link_color' => '#fff7ed',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'forest' => array(
                'name' => __('Forest', 'logindesignerwp'),
                'category' => 'nature',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #14532d, #166534)',
                    'form_bg' => '#f0fdf4',
                    'form_border' => '1px solid #86efac',
                    'input_bg' => '#ffffff',
                    'button_bg' => '#16a34a',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#14532d',
                    'background_gradient_2' => '#166534',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#f0fdf4',
                    'form_border_radius' => 12,
                    'form_border_color' => '#86efac',
                    'label_text_color' => '#14532d',
                    'input_bg_color' => '#ffffff',
                    'input_text_color' => '#166534',
                    'input_border_color' => '#bbf7d0',
                    'button_bg' => '#16a34a',
                    'button_bg_hover' => '#15803d',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 8,
                    'below_form_link_color' => '#dcfce7',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'ocean' => array(
                'name' => __('Ocean', 'logindesignerwp'),
                'category' => 'nature',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #0891b2, #164e63)',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #a5f3fc',
                    'input_bg' => '#ecfeff',
                    'button_bg' => '#0891b2',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#0891b2',
                    'background_gradient_2' => '#164e63',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 16,
                    'form_border_color' => '#a5f3fc',
                    'label_text_color' => '#164e63',
                    'input_bg_color' => '#ecfeff',
                    'input_text_color' => '#164e63',
                    'input_border_color' => '#67e8f9',
                    'button_bg' => '#0891b2',
                    'button_bg_hover' => '#0e7490',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 8,
                    'below_form_link_color' => '#cffafe',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'lavender_dream' => array(
                'name' => __('Lavender Dream', 'logindesignerwp'),
                'category' => 'nature',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#f3e8ff',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #d8b4fe',
                    'input_bg' => '#faf5ff',
                    'button_bg' => '#a855f7',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#f3e8ff',
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 20,
                    'form_border_color' => '#d8b4fe',
                    'label_text_color' => '#6b21a8',
                    'input_bg_color' => '#faf5ff',
                    'input_text_color' => '#581c87',
                    'input_border_color' => '#e9d5ff',
                    'button_bg' => '#a855f7',
                    'button_bg_hover' => '#9333ea',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 12,
                    'below_form_link_color' => '#7e22ce',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // RETRO / CREATIVE
            // ============================================
            'midnight' => array(
                'name' => __('Midnight', 'logindesignerwp'),
                'category' => 'creative',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #1e1b4b, #312e81)',
                    'form_bg' => '#0f0a1e',
                    'form_border' => '1px solid #4c1d95',
                    'input_bg' => '#1e1b4b',
                    'button_bg' => '#7c3aed',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#1e1b4b',
                    'background_gradient_2' => '#312e81',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#0f0a1e',
                    'form_border_radius' => 16,
                    'form_border_color' => '#4c1d95',
                    'label_text_color' => '#c4b5fd',
                    'input_bg_color' => '#1e1b4b',
                    'input_text_color' => '#f5f3ff',
                    'input_border_color' => '#6d28d9',
                    'button_bg' => '#7c3aed',
                    'button_bg_hover' => '#6d28d9',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 999,
                    'below_form_link_color' => '#c4b5fd',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'tech' => array(
                'name' => __('Tech', 'logindesignerwp'),
                'category' => 'creative',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#18181b',
                    'form_bg' => '#27272a',
                    'form_border' => '1px solid #3f3f46',
                    'input_bg' => '#18181b',
                    'button_bg' => '#a855f7',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#18181b',
                    'form_bg_color' => '#27272a',
                    'form_border_radius' => 16,
                    'form_border_color' => '#3f3f46',
                    'label_text_color' => '#a1a1aa',
                    'input_bg_color' => '#18181b',
                    'input_text_color' => '#fafafa',
                    'input_border_color' => '#52525b',
                    'button_bg' => '#a855f7',
                    'button_bg_hover' => '#9333ea',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 8,
                    'below_form_link_color' => '#a1a1aa',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'creative' => array(
                'name' => __('Creative', 'logindesignerwp'),
                'category' => 'creative',
                'is_pro' => true,
                'preview' => array(
                    'bg' => 'linear-gradient(135deg, #f97316, #ec4899)',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #fecdd3',
                    'input_bg' => '#fff1f2',
                    'button_bg' => '#ec4899',
                ),
                'settings' => array(
                    'background_mode' => 'gradient',
                    'background_gradient_1' => '#f97316',
                    'background_gradient_2' => '#ec4899',
                    'gradient_type' => 'linear',
                    'gradient_angle' => 135,
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 24,
                    'form_border_color' => '#fecdd3',
                    'label_text_color' => '#831843',
                    'input_bg_color' => '#fff1f2',
                    'input_text_color' => '#831843',
                    'input_border_color' => '#fda4af',
                    'button_bg' => '#ec4899',
                    'button_bg_hover' => '#db2777',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 999,
                    'below_form_link_color' => '#fff1f2',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'ruby_red' => array(
                'name' => __('Ruby Red', 'logindesignerwp'),
                'category' => 'creative',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#7f1d1d',
                    'form_bg' => '#991b1b',
                    'form_border' => '1px solid #ef4444',
                    'input_bg' => '#7f1d1d',
                    'button_bg' => '#f87171',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#7f1d1d',
                    'form_bg_color' => '#991b1b',
                    'form_border_radius' => 8,
                    'form_border_color' => '#ef4444',
                    'label_text_color' => '#fecaca',
                    'input_bg_color' => '#7f1d1d',
                    'input_text_color' => '#ffffff',
                    'input_border_color' => '#b91c1c',
                    'button_bg' => '#f87171',
                    'button_bg_hover' => '#ef4444',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 4,
                    'below_form_link_color' => '#fecaca',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'elegant' => array(
                'name' => __('Elegant', 'logindesignerwp'),
                'category' => 'minimal',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#1c1917',
                    'form_bg' => '#fafaf9',
                    'form_border' => '1px solid #d6d3d1',
                    'input_bg' => '#ffffff',
                    'button_bg' => '#78716c',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#1c1917',
                    'form_bg_color' => '#fafaf9',
                    'form_border_radius' => 8,
                    'form_border_color' => '#d6d3d1',
                    'label_text_color' => '#44403c',
                    'input_bg_color' => '#ffffff',
                    'input_text_color' => '#1c1917',
                    'input_border_color' => '#a8a29e',
                    'button_bg' => '#78716c',
                    'button_bg_hover' => '#57534e',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 4,
                    'below_form_link_color' => '#a8a29e',
                    'logo_bottom_margin' => 25,
                ),
            ),
            // ============================================
            // NEW: COFFEE
            // ============================================
            'coffee' => array(
                'name' => __('Coffee Shop', 'logindesignerwp'),
                'category' => 'creative',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#3f2e3e',
                    'form_bg' => '#efebd8',
                    'form_border' => '1px solid #a78295',
                    'input_bg' => '#ffffff',
                    'button_bg' => '#331d2c',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#3f2e3e',
                    'form_bg_color' => '#efebd8',
                    'form_border_radius' => 8,
                    'form_border_color' => '#a78295',
                    'label_text_color' => '#331d2c',
                    'input_bg_color' => '#ffffff',
                    'input_text_color' => '#3f2e3e',
                    'input_border_color' => '#a78295',
                    'button_bg' => '#331d2c',
                    'button_bg_hover' => '#3f2e3e',
                    'button_text_color' => '#efebd8',
                    'button_border_radius' => 4,
                    'below_form_link_color' => '#efebd8',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'mint' => array(
                'name' => __('Mint Fresh', 'logindesignerwp'),
                'category' => 'nature',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#d1fae5',
                    'form_bg' => '#ffffff',
                    'form_border' => '1px solid #34d399',
                    'input_bg' => '#f0fdf4',
                    'button_bg' => '#10b981',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#d1fae5',
                    'form_bg_color' => '#ffffff',
                    'form_border_radius' => 20,
                    'form_border_color' => '#34d399',
                    'label_text_color' => '#065f46',
                    'input_bg_color' => '#f0fdf4',
                    'input_text_color' => '#064e3b',
                    'input_border_color' => '#6ee7b7',
                    'button_bg' => '#10b981',
                    'button_bg_hover' => '#059669',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 999,
                    'below_form_link_color' => '#065f46',
                    'logo_bottom_margin' => 25,
                ),
            ),
            'solar' => array(
                'name' => __('Solar', 'logindesignerwp'),
                'category' => 'modern',
                'is_pro' => true,
                'preview' => array(
                    'bg' => '#1f2937',
                    'form_bg' => '#111827',
                    'form_border' => '1px solid #f97316',
                    'input_bg' => '#374151',
                    'button_bg' => '#f97316',
                ),
                'settings' => array(
                    'background_mode' => 'solid',
                    'background_color' => '#1f2937',
                    'form_bg_color' => '#111827',
                    'form_border_radius' => 8,
                    'form_border_color' => '#f97316',
                    'label_text_color' => '#fed7aa',
                    'input_bg_color' => '#374151',
                    'input_text_color' => '#f9fafb',
                    'input_border_color' => '#fb923c',
                    'button_bg' => '#f97316',
                    'button_bg_hover' => '#ea580c',
                    'button_text_color' => '#ffffff',
                    'button_border_radius' => 6,
                    'below_form_link_color' => '#fed7aa',
                    'logo_bottom_margin' => 25,
                ),
            ),
        );
    }
}
